[package]
name = "reth-monitor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Transaction and block monitoring for X Layer"

[lints]
workspace = true

[dependencies]
alloy-primitives.workspace = true
tracing.workspace = true

