[package]
name = "seidb-wal"
version = "0.1.0"
edition = "2024"

[dependencies]
seidb-common = { workspace = true }
seidb-traits = { workspace = true }
seidb-proto = { workspace = true }
prost = { workspace = true }
crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }
crc32fast = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
