#!/usr/bin/env bash
# Generate minimal X Layer genesis.json by removing 'alloc' field
# Usage: ./gen_genesis_xlayer.sh <network> <genesis-file>

set -e

# Cleanup function
cleanup() {
    if [ -n "$TEMP_DIR" ] && [ -d "$TEMP_DIR" ]; then
        rm -rf "$TEMP_DIR"
    fi
}
trap cleanup EXIT

# Check arguments
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <network> <genesis-file>"
    echo ""
    echo "Arguments:"
    echo "  network       Network type: mainnet, testnet, devnet"
    echo "  genesis-file  Path to full genesis.json or .tar.gz archive"
    echo ""
    echo "Example:"
    echo "  $0 mainnet /path/to/genesis-mainnet.json"
    echo "  $0 testnet /path/to/genesis-testnet.tar.gz"
    exit 1
fi

NETWORK="$1"
INPUT_FILE="$2"
OUTPUT_FILE="genesis/xlayer_${NETWORK}.json"

# Validate network type
if [[ -z "$NETWORK" ]]; then
    echo "❌ Network name cannot be empty"
    exit 1
fi

# Check input file exists
if [ ! -f "$INPUT_FILE" ]; then
    echo "❌ Input file not found: $INPUT_FILE"
    exit 1
fi

echo "=== X Layer Genesis Generator ==="
echo ""

# Handle compressed archives
GENESIS_FILE="$INPUT_FILE"
if [[ "$INPUT_FILE" == *.tar.gz ]] || [[ "$INPUT_FILE" == *.tgz ]]; then
    echo "📦 Detected compressed archive, extracting..."
    TEMP_DIR=$(mktemp -d)
    tar -xzf "$INPUT_FILE" -C "$TEMP_DIR"

    # Find the genesis JSON file
    GENESIS_FILE=$(find "$TEMP_DIR" -name "*.json" -type f | head -1)
    if [ -z "$GENESIS_FILE" ]; then
        echo "❌ No JSON file found in archive"
        exit 1
    fi
    echo "✅ Extracted: $(basename $GENESIS_FILE)"
    echo ""
fi

# Prepare genesis file for op-reth - set number field from legacyXLayerBlock
echo "🔧 Preparing genesis for op-reth..."
LEGACY_BLOCK=$(jq -r '.config.legacyXLayerBlock // "null"' "$GENESIS_FILE")

if [ "$LEGACY_BLOCK" != "null" ] && [ -n "$LEGACY_BLOCK" ]; then
    BLOCK_HEX=$(printf '0x%x' $LEGACY_BLOCK)
    echo "   Setting genesis block number to $LEGACY_BLOCK ($BLOCK_HEX)"

    # Update genesis file with correct block number
    TEMP_GENESIS=$(mktemp)
    jq ".number = \"$BLOCK_HEX\"" "$GENESIS_FILE" > "$TEMP_GENESIS"
    mv "$TEMP_GENESIS" "$GENESIS_FILE"
    echo "✅ Genesis block number updated"
else
    echo "ℹ️  No legacyXLayerBlock found, using original number field"
fi
echo ""

# Get file stats
SIZE_MB=$(du -m "$GENESIS_FILE" | cut -f1)
ALLOC_COUNT=$(jq '.alloc | length' "$GENESIS_FILE")
CHAIN_ID=$(jq -r '.config.chainId' "$GENESIS_FILE")
echo "Input:  $(basename $GENESIS_FILE)"
echo "        Chain ID: $CHAIN_ID, Size: ${SIZE_MB} MB, Alloc: ${ALLOC_COUNT} accounts"

# Generate minimal genesis with metadata comment at the beginning
mkdir -p genesis
jq --arg note "Generated by gen_genesis_xlayer.sh - alloc field removed for fast loading. Full alloc is in database after init-state." \
   '{_comment: $note} + del(.alloc)' "$GENESIS_FILE" > "$OUTPUT_FILE"

echo "Output: $OUTPUT_FILE ($(du -k "$OUTPUT_FILE" | cut -f1) KB)"
echo ""

# Verify consistency - compare all fields except alloc
echo "Verifying consistency (comparing key fields)..."
TEMP_ORIGINAL=$(mktemp)
TEMP_MINIMAL=$(mktemp)

# Extract and sort for comparison
jq 'del(.alloc, ._comment) | walk(if type == "object" then to_entries | sort_by(.key) | from_entries else . end)' "$GENESIS_FILE" > "$TEMP_ORIGINAL"
jq 'del(._comment) | walk(if type == "object" then to_entries | sort_by(.key) | from_entries else . end)' "$OUTPUT_FILE" > "$TEMP_MINIMAL"

# Print key field comparison
echo ""
echo "Key field comparison:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
printf "%-20s | %-40s | %-40s\n" "Field" "Original" "Minimal"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Get all top-level keys from original (excluding alloc)
ALL_KEYS=$(jq -r 'keys[] | select(. != "alloc")' "$GENESIS_FILE" | sort)

# Compare all fields
while IFS= read -r field; do
    ORIG_VAL=$(jq -r ".$field // \"N/A\"" "$TEMP_ORIGINAL" | head -c 40)
    MIN_VAL=$(jq -r ".$field // \"N/A\"" "$TEMP_MINIMAL" | head -c 40)

    if [ "$ORIG_VAL" = "$MIN_VAL" ]; then
        printf "%-20s | %-40s | %-40s ✓\n" "$field" "$ORIG_VAL" "$MIN_VAL"
    else
        printf "%-20s | %-40s | %-40s ✗\n" "$field" "$ORIG_VAL" "$MIN_VAL"
    fi
done <<< "$ALL_KEYS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Full diff check
if diff -q "$TEMP_ORIGINAL" "$TEMP_MINIMAL" > /dev/null; then
    echo "✅ Full verification passed: All fields match"
else
    echo "❌ Verification failed: Files differ"
    echo ""
    echo "Showing differences:"
    diff -u "$TEMP_ORIGINAL" "$TEMP_MINIMAL" | head -50 || true
    rm -f "$TEMP_ORIGINAL" "$TEMP_MINIMAL"
    exit 1
fi

rm -f "$TEMP_ORIGINAL" "$TEMP_MINIMAL"

# Summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Success! Generated: $OUTPUT_FILE"
echo ""
echo "   Removed: alloc field (${ALLOC_COUNT} accounts, ~${SIZE_MB} MB)"
echo "   Added:   _comment field explaining the removal"
echo ""
echo "Next: Get genesis constants (takes ~40s):"
echo "  op-reth --chain $GENESIS_FILE node --help 2>&1 | grep -A 10 'GENESIS CONSTANTS'"
echo ""
echo "Then copy constants to: src/xlayer_${NETWORK}.rs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
