#!/usr/bin/env bash
# Generate minimal X Layer genesis.json by removing 'alloc' field
# Usage: ./gen_genesis_xlayer.sh <network> <genesis-file>

set -e

# Check arguments
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <network> <genesis-file>"
    echo ""
    echo "Arguments:"
    echo "  network       Network type: mainnet, testnet, devnet"
    echo "  genesis-file  Path to full genesis.json"
    echo ""
    echo "Example:"
    echo "  $0 mainnet /path/to/genesis-mainnet.json"
    exit 1
fi

NETWORK="$1"
GENESIS_FILE="$2"
OUTPUT_FILE="genesis/xlayer_${NETWORK}.json"

# Validate network type (accept any name for flexibility)
# Common: mainnet, testnet, devnet
if [[ -z "$NETWORK" ]]; then
    echo "❌ Network name cannot be empty"
    exit 1
fi

# Check input file exists
if [ ! -f "$GENESIS_FILE" ]; then
    echo "❌ Genesis file not found: $GENESIS_FILE"
    exit 1
fi

echo "=== X Layer Genesis Generator ==="
echo ""

# Get file stats
SIZE_MB=$(du -m "$GENESIS_FILE" | cut -f1)
ALLOC_COUNT=$(jq '.alloc | length' "$GENESIS_FILE")
CHAIN_ID=$(jq -r '.config.chainId' "$GENESIS_FILE")
echo "Input:  $GENESIS_FILE"
echo "        Chain ID: $CHAIN_ID, Size: ${SIZE_MB} MB, Alloc: ${ALLOC_COUNT} accounts"

# Generate minimal genesis with metadata comment at the beginning
mkdir -p genesis
jq --arg note "Generated by gen_genesis_xlayer.sh - alloc field removed for fast loading. Full alloc is in database after init-state." \
   '{_comment: $note} + del(.alloc)' "$GENESIS_FILE" > "$OUTPUT_FILE"

echo "Output: $OUTPUT_FILE ($(du -k "$OUTPUT_FILE" | cut -f1) KB)"
echo ""

# Verify consistency - compare all fields except alloc
echo "Verifying consistency (comparing key fields)..."
TEMP_ORIGINAL=$(mktemp)
TEMP_MINIMAL=$(mktemp)

# Extract and sort for comparison
jq 'del(.alloc, ._comment) | walk(if type == "object" then to_entries | sort_by(.key) | from_entries else . end)' "$GENESIS_FILE" > "$TEMP_ORIGINAL"
jq 'del(._comment) | walk(if type == "object" then to_entries | sort_by(.key) | from_entries else . end)' "$OUTPUT_FILE" > "$TEMP_MINIMAL"

# Print key field comparison
echo ""
echo "Key field comparison:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
printf "%-20s | %-40s | %-40s\n" "Field" "Original" "Minimal"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Get all top-level keys from original (excluding alloc)
ALL_KEYS=$(jq -r 'keys[] | select(. != "alloc")' "$GENESIS_FILE" | sort)

# Compare all fields
while IFS= read -r field; do
    ORIG_VAL=$(jq -r ".$field // \"N/A\"" "$TEMP_ORIGINAL" | head -c 40)
    MIN_VAL=$(jq -r ".$field // \"N/A\"" "$TEMP_MINIMAL" | head -c 40)

    if [ "$ORIG_VAL" = "$MIN_VAL" ]; then
        printf "%-20s | %-40s | %-40s ✓\n" "$field" "$ORIG_VAL" "$MIN_VAL"
    else
        printf "%-20s | %-40s | %-40s ✗\n" "$field" "$ORIG_VAL" "$MIN_VAL"
    fi
done <<< "$ALL_KEYS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Full diff check
if diff -q "$TEMP_ORIGINAL" "$TEMP_MINIMAL" > /dev/null; then
    echo "✅ Full verification passed: All fields match"
else
    echo "❌ Verification failed: Files differ"
    echo ""
    echo "Showing differences:"
    diff -u "$TEMP_ORIGINAL" "$TEMP_MINIMAL" | head -50 || true
    rm -f "$TEMP_ORIGINAL" "$TEMP_MINIMAL"
    exit 1
fi

rm -f "$TEMP_ORIGINAL" "$TEMP_MINIMAL"

# Summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Success! Generated: $OUTPUT_FILE"
echo ""
echo "   Removed: alloc field (${ALLOC_COUNT} accounts, ~${SIZE_MB} MB)"
echo "   Added:   _comment field explaining the removal"
echo ""
echo "Next: Get genesis constants (takes ~40s):"
echo "  op-reth --chain $GENESIS_FILE node --help 2>&1 | grep -A 10 'GENESIS CONSTANTS'"
echo ""
echo "Then copy constants to: src/xlayer_${NETWORK}.rs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
