//! End-to-end Go<->Rust behavior comparison and consistency tests.
//!
//! - `test_e2e_go_compat_100_blocks`: processes the same deterministic changeset sequence as the Go
//!   golden generator, then compares per-block commit info hashes.
//! - `test_e2e_deterministic_consistency`: same changeset sequence twice -> same hash.
//! - `test_e2e_close_reopen_consistency`: close -> reopen -> same hash.
//! - `test_e2e_rollback_consistency`: rollback to block 50 -> hash matches recorded value.
//! - `test_e2e_500_blocks_cosmos_only`: 500 blocks, no panic, final version == 500.
//! - `test_e2e_close_reopen_continue`: 100 blocks -> close -> reopen -> 100 more -> version 200.

use seidb::db::SeiDb;
use seidb_common::config::{MemIavlConfig, StateCommitConfig, WriteMode};
use seidb_proto::{ChangeSet, KvPair, NamedChangeSet};
use std::collections::HashMap;
use tempfile::tempdir;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Build a test SC config with snapshots disabled.
fn test_sc_config() -> StateCommitConfig {
    StateCommitConfig {
        write_mode: WriteMode::CosmosOnly,
        memiavl: MemIavlConfig { snapshot_interval: 0, ..Default::default() },
        ..Default::default()
    }
}

/// Open a SeiDb for testing with bank+staking stores.
fn open_test_db(home: &str) -> SeiDb {
    let mut db = SeiDb::open(home, test_sc_config(), None).unwrap();
    db.initialize(&["bank".into(), "staking".into()]);
    db.load_version(0).unwrap();
    db
}

/// Generate the deterministic changeset for a given block number.
/// This must exactly match the Go golden generator algorithm.
fn generate_changesets(block: i64) -> Vec<NamedChangeSet> {
    let seed = (block as u64).wrapping_mul(2654435761);

    let mut bank_pairs: Vec<KvPair> = (0..5)
        .map(|i| KvPair {
            delete: false,
            key: format!("bank_key_{block}_{i}").into_bytes(),
            value: format!("bank_value_{block}_{i}_{:x}", (seed + i as u64) & 0xFFFF).into_bytes(),
        })
        .collect();

    let staking_pairs: Vec<KvPair> = (0..3)
        .map(|i| KvPair {
            delete: false,
            key: format!("staking_key_{block}_{i}").into_bytes(),
            value: format!("staking_value_{block}_{i}_{:x}", (seed + i as u64 + 100) & 0xFFFF)
                .into_bytes(),
        })
        .collect();

    // Every 20 blocks, delete a key from 20 blocks ago
    if block > 20 && block % 20 == 0 {
        bank_pairs.push(KvPair {
            delete: true,
            key: format!("bank_key_{}_0", block - 20).into_bytes(),
            value: vec![],
        });
    }

    vec![
        NamedChangeSet { name: "bank".into(), changeset: Some(ChangeSet { pairs: bank_pairs }) },
        NamedChangeSet {
            name: "staking".into(),
            changeset: Some(ChangeSet { pairs: staking_pairs }),
        },
    ]
}

/// Process N blocks on a SeiDb, returning per-block (version, store_hashes) records.
fn process_blocks(
    seidb: &mut SeiDb,
    start_block: i64,
    end_block: i64,
) -> Vec<(i64, HashMap<String, String>)> {
    let mut records = Vec::new();
    for block in start_block..=end_block {
        let cs = generate_changesets(block);
        seidb.sc_mut().apply_change_sets(&cs).unwrap();
        let version = seidb.sc_mut().commit().unwrap();

        let info = seidb.sc().last_commit_info();
        let mut store_hashes = HashMap::new();
        for si in &info.store_infos {
            if let Some(ref cid) = si.commit_id {
                let hex_hash: String = cid.hash.iter().map(|b| format!("{b:02x}")).collect();
                store_hashes.insert(si.name.clone(), hex_hash);
            }
        }
        records.push((version, store_hashes));
    }
    records
}

// ---------------------------------------------------------------------------
// Golden data structure
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize, Debug)]
struct BlockGolden {
    #[allow(dead_code)]
    block: i64,
    version: i64,
    store_hashes: HashMap<String, String>,
}

// ---------------------------------------------------------------------------
// Test: Go compatibility (golden comparison)
// ---------------------------------------------------------------------------

#[test]
fn test_e2e_go_compat_100_blocks() {
    // Load golden output generated by Go
    let golden_path = concat!(env!("CARGO_MANIFEST_DIR"), "/testdata/e2e_golden_100blocks.json");
    let golden_data = std::fs::read_to_string(golden_path).expect("golden file not found");
    let golden: Vec<BlockGolden> = serde_json::from_str(&golden_data).unwrap();
    assert_eq!(golden.len(), 100);

    let dir = tempdir().unwrap();
    let home = dir.path().to_string_lossy().to_string();
    let mut seidb = open_test_db(&home);

    let records = process_blocks(&mut seidb, 1, 100);
    assert_eq!(records.len(), 100);

    for (i, (version, store_hashes)) in records.iter().enumerate() {
        let expected = &golden[i];
        let block = (i + 1) as i64;

        assert_eq!(
            *version, expected.version,
            "version mismatch at block {block}: rust={version} go={}",
            expected.version
        );

        for (store_name, go_hash) in &expected.store_hashes {
            let rust_hash = store_hashes.get(store_name).unwrap_or(&String::new()).clone();
            assert_eq!(
                rust_hash, *go_hash,
                "hash mismatch for store '{store_name}' at block {block}:\n  Go:   {go_hash}\n  Rust: {rust_hash}"
            );
        }
    }

    seidb.close().unwrap();
}

// ---------------------------------------------------------------------------
// Test: Deterministic consistency (same sequence twice -> same hashes)
// ---------------------------------------------------------------------------

#[test]
fn test_e2e_deterministic_consistency() {
    // Run 1
    let dir1 = tempdir().unwrap();
    let home1 = dir1.path().to_string_lossy().to_string();
    let mut db1 = open_test_db(&home1);
    let records1 = process_blocks(&mut db1, 1, 50);
    db1.close().unwrap();

    // Run 2
    let dir2 = tempdir().unwrap();
    let home2 = dir2.path().to_string_lossy().to_string();
    let mut db2 = open_test_db(&home2);
    let records2 = process_blocks(&mut db2, 1, 50);
    db2.close().unwrap();

    // Compare
    assert_eq!(records1.len(), records2.len());
    for (i, ((v1, h1), (v2, h2))) in records1.iter().zip(records2.iter()).enumerate() {
        let block = (i + 1) as i64;
        assert_eq!(v1, v2, "version mismatch at block {block}");
        assert_eq!(h1, h2, "hash mismatch at block {block}");
    }
}

// ---------------------------------------------------------------------------
// Test: Close/reopen consistency
// ---------------------------------------------------------------------------

#[test]
fn test_e2e_close_reopen_consistency() {
    let dir = tempdir().unwrap();
    let home = dir.path().to_string_lossy().to_string();

    // Phase 1: process 100 blocks and record hashes
    let records_before;
    {
        let mut seidb = open_test_db(&home);
        records_before = process_blocks(&mut seidb, 1, 100);
        assert_eq!(records_before.len(), 100);
        seidb.close().unwrap();
    }

    // Phase 2: reopen, load version 100, check last_commit_info
    {
        let mut seidb = SeiDb::open(&home, test_sc_config(), None).unwrap();
        seidb.initialize(&["bank".into(), "staking".into()]);
        seidb.load_version(100).unwrap();
        assert_eq!(seidb.version(), 100);

        let info = seidb.sc().last_commit_info();
        assert_eq!(info.version, 100);

        // Verify store hashes match what we recorded for block 100
        let (_, expected_hashes) = &records_before[99];
        for si in &info.store_infos {
            if let Some(ref cid) = si.commit_id {
                let rust_hash: String = cid.hash.iter().map(|b| format!("{b:02x}")).collect();
                if let Some(expected) = expected_hashes.get(&si.name) {
                    assert_eq!(
                        &rust_hash, expected,
                        "hash mismatch for store '{}' after reopen",
                        si.name
                    );
                }
            }
        }

        seidb.close().unwrap();
    }
}

// ---------------------------------------------------------------------------
// Test: Rollback consistency
// ---------------------------------------------------------------------------

#[test]
fn test_e2e_rollback_consistency() {
    let dir = tempdir().unwrap();
    let home = dir.path().to_string_lossy().to_string();

    // Process 100 blocks, record hash at block 50
    let mut seidb = open_test_db(&home);
    let records = process_blocks(&mut seidb, 1, 100);
    let (_, hash_at_50) = &records[49];
    assert_eq!(seidb.version(), 100);

    // Rollback to version 50
    seidb.sc_mut().rollback(50).unwrap();
    seidb.load_version(50).unwrap();
    assert_eq!(seidb.version(), 50);

    // Verify the hash at version 50 matches
    let info = seidb.sc().last_commit_info();
    assert_eq!(info.version, 50);

    for si in &info.store_infos {
        if let Some(ref cid) = si.commit_id {
            let rust_hash: String = cid.hash.iter().map(|b| format!("{b:02x}")).collect();
            if let Some(expected) = hash_at_50.get(&si.name) {
                assert_eq!(
                    &rust_hash, expected,
                    "hash mismatch for store '{}' after rollback to 50",
                    si.name
                );
            }
        }
    }

    seidb.close().unwrap();
}

// ---------------------------------------------------------------------------
// Test: 500 blocks (load test)
// ---------------------------------------------------------------------------

#[test]
fn test_e2e_500_blocks_cosmos_only() {
    let dir = tempdir().unwrap();
    let home = dir.path().to_string_lossy().to_string();
    let mut seidb = open_test_db(&home);

    for block in 1..=500i64 {
        let cs = generate_changesets(block);
        seidb.sc_mut().apply_change_sets(&cs).unwrap();
        let version = seidb.sc_mut().commit().unwrap();
        assert_eq!(version, block);
    }

    assert_eq!(seidb.version(), 500);

    let info = seidb.sc().last_commit_info();
    assert_eq!(info.version, 500);
    // Verify both stores have non-empty hashes
    for si in &info.store_infos {
        if let Some(ref cid) = si.commit_id {
            assert!(!cid.hash.is_empty(), "store '{}' has empty hash at block 500", si.name);
        }
    }

    seidb.close().unwrap();
}

// ---------------------------------------------------------------------------
// Test: Close/reopen and continue
// ---------------------------------------------------------------------------

#[test]
fn test_e2e_close_reopen_continue() {
    let dir = tempdir().unwrap();
    let home = dir.path().to_string_lossy().to_string();

    // Phase 1: process 100 blocks, close
    {
        let mut seidb = open_test_db(&home);
        process_blocks(&mut seidb, 1, 100);
        assert_eq!(seidb.version(), 100);
        seidb.close().unwrap();
    }

    // Phase 2: reopen, load version 100, process 100 more blocks
    {
        let mut seidb = SeiDb::open(&home, test_sc_config(), None).unwrap();
        seidb.initialize(&["bank".into(), "staking".into()]);
        seidb.load_version(100).unwrap();
        assert_eq!(seidb.version(), 100);

        // Continue from block 101 to 200
        for block in 101..=200i64 {
            let cs = generate_changesets(block);
            seidb.sc_mut().apply_change_sets(&cs).unwrap();
            let version = seidb.sc_mut().commit().unwrap();
            assert_eq!(version, block);
        }

        assert_eq!(seidb.version(), 200);
        seidb.close().unwrap();
    }
}
