[package]
name = "mptdb-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
mptdb-common = { workspace = true }
mptdb-traits = { workspace = true }
mptdb-proto = { workspace = true }
mptdb-wal = { workspace = true }
rocksdb = { workspace = true }
reth-libmdbx = { workspace = true }
crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
criterion.workspace = true

[[bench]]
name = "mvcc_bench"
harness = false
