[package]
name = "mptdb-sc"
version = "0.1.0"
edition = "2024"

[dependencies]
mptdb-common = { workspace = true }
mptdb-traits = { workspace = true }
mptdb-engine = { workspace = true }
mptdb-ss = { workspace = true }
mptdb-proto = { workspace = true }
rayon = { workspace = true }
crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
fs4 = { workspace = true }
alloy-primitives = { workspace = true, features = ["serde"] }
alloy-rlp = { workspace = true, features = ["derive"] }
alloy-trie = { workspace = true, features = ["ethereum"] }
revm-database = { workspace = true }
revm-state = { workspace = true }
reth-trie-common = { workspace = true }
reth-primitives-traits = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
schnellru = { workspace = true }
bincode = { workspace = true }
postcard = { workspace = true }
crc32fast = { workspace = true }
memmap2 = { workspace = true }

[features]
default = []
asm-keccak = ["alloy-primitives/asm-keccak"]

[dev-dependencies]
tempfile = { workspace = true }
criterion.workspace = true
rand = { workspace = true }
reth-trie = { workspace = true, features = ["test-utils"] }
reth-primitives-traits = { workspace = true, features = ["test-utils"] }

[[bench]]
name = "mpt_parallel_bench"
harness = false

[[bench]]
name = "mpt_commit_bench"
harness = false
