[package]
name = "reth-db-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-db-api.workspace = true
reth-db.workspace = true
reth-provider = { workspace = true, features = ["test-utils"] }
reth-primitives-traits.workspace = true
reth-config.workspace = true
reth-trie.workspace = true
reth-trie-db.workspace = true
reth-etl.workspace = true
reth-codecs.workspace = true
reth-stages-types.workspace = true
reth-storage-api.workspace = true
reth-fs-util.workspace = true
reth-node-types.workspace = true
reth-static-file-types.workspace = true
reth-execution-errors.workspace = true
reth-trie-common.workspace = true
alloy-trie.workspace = true
triedb.workspace = true
# eth
alloy-consensus.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true

# misc
eyre.workspace = true
thiserror.workspace = true
boyer-moore-magiclen.workspace = true
rand = "0.8"

# io
serde.workspace = true
serde_json.workspace = true

# tracing
tracing.workspace = true

# Add tempdir for the binary
tempdir = "0.3.7"

[features]
default = []
trie-db-ext = []
bin-utils = ["reth-provider/test-utils"]

[dev-dependencies]
reth-db = { workspace = true, features = ["mdbx"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-storage-api.workspace = true
tempdir = "0.3.7"
rand = "0.8"
criterion = { workspace = true }


[[bench]]
name = "state_root_comparison"
harness = false
required-features = ["trie-db-ext"]

[[bin]]
name = "state_root_runner"
path = "src/bin/state_root_runner.rs"
required-features = ["trie-db-ext"]   # so you can also run the TrieDB method

[lints]
workspace = true
