[package]
name = "reth-realtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A realtime library for op-reth."

[lints]
workspace = true

[dependencies]
rdkafka = "0.38" 
tokio = { workspace = true, features = ["sync", "time", "macros"] }
futures = { workspace = true }
tracing = { workspace = true } 
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reth-optimism-flashblocks = { workspace = true }
alloy-rpc-types-engine = { workspace = true }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
